version: '3.8'

services:
  fileditch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOMAIN=http://localhost:3000
      - SITE_PASSWORD=admin123
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=10
      - ALLOWED_TYPES=all
      - RANDOM_STRING_LENGTH=32
      - DB_PATH=/app/data/fileditch.db
    volumes:
      - fileditch_uploads:/app/uploads
      - fileditch_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  fileditch_uploads:
    name: fileditch_uploads
  fileditch_data:
    name: fileditch_data